name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  libraries:
    path: '../libraries'
  module_start:
    path: '../module_start'
  module_design_system:
    path: '../module_design_system'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  assets:
    - 'assets/mocks/'

flutter_intl:
  enabled: true
  arb_dir: lib/internationalization
  output_dir: lib/internationalization/generated
  class_name: CoreLocalizations
  synthetic-package: false
  main_locale: pt_BR
