name: module_design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: '../core'
  
  libraries:
    path: '../libraries'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  mobx_codegen: ^2.7.2

flutter:
  uses-material-design: true

  assets:
    - 'assets/svgs/'
    - 'assets/images/'
    - 'assets/animations/'

flutter_intl:
  enabled: true
  arb_dir: lib/internationalization
  output_dir: lib/internationalization/generated
  class_name: DSLocalizations
  synthetic-package: false
  main_locale: pt_BR