include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    must_call_super: ignore
    no_logic_in_create_state: ignore
    prefer_collection_literals: ignore
    prefer_const_constructors_in_immutables: ignore
    unused_field: ignore
    use_key_in_widget_constructors: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
